FROM debian:latest

RUN apt-get update && \
    apt-get install -y \
      curl \
      wget \
      vim \
      python-pip \
      git \
      net-tools \
      virtualenv \
      && pip install 'pyOpenSSL' 
